### ISSUE TITLE
功能请求，获取基本信息的API

### ISSUE THREAD

**Issue by junyuyuan** [sqzw-x/mdcx#281]
### 这是一个新的功能请求吗？

- [X] 我已搜索现有问题

### 想要的变化

是否能够提供一个获取首页当前状态数据的API接口供我配置Homepage使用？
![image](https://github.com/user-attachments/assets/6112fd3d-3741-43be-b4ae-12faf1298974)
当前运行状态（转移中，转移完成），转移数量之类的数据
```
            type: customapi
            url: API URL
            method: GET
            headers:
              X-API-TOKEN: Token
            mappings:
```
